name: Daily Market Monitor

# Run daily at midnight UTC
on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-prediction:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper commits
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn joblib yfinance xgboost lightgbm
      
      - name: Run Market Monitor
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: |
          python scripts/monitor.py
      
      - name: Commit and push logs
        run: |
          git config --global user.name "Market Monitor Bot"
          git config --global user.email "bot@marketmonitor.com"
          git add logs/predictions.log
          git diff --quiet && git diff --staged --quiet || (git commit -m "📊 Automated update: $(date +'%Y-%m-%d %H:%M:%S')" && git push)
      
      - name: Upload logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: prediction-logs
          path: logs/predictions.log
          retention-days: 30
